name: ci
on:
  push:
  workflow_dispatch:

jobs:

  build_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: eriweb-demos/action-demo-dockerfile@main
      - run: echo "we built stuff"

  other_step:
    runs-on: ubuntu-latest
    needs: build_code
    steps:
      - run: echo "this is another step!"

  test_code:
    runs-on: ubuntu-latest
    needs: build_code
    steps:
      - uses: actions/checkout@v3
      - uses: eriweb-demos/action-demo-nodejs@main
      - run: echo "all tests are okay!"
    
  another_step:
    runs-on: ubuntu-latest
    steps:
      - run: echo "we need more steps!"

  deploy:
    needs: [test_code, other_step, another_step]
    uses: eriweb-demos/workflow-reusable/.github/workflows/demo.yaml@main
    with:
      name: 'advanced workflow'