name: ci
on:
  push:
  workflow_dispatch:

jobs:

  build_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: eriweb-demos/action-demo-dockerfile@main
      - run: echo "we built stuff"

  test_code:
    runs-on: ubuntu-latest
    needs: build_code
    steps:
      - uses: actions/checkout@v3
      - uses: eriweb-demos/action-demo-nodejs@main
      - run: echo "all tests are okay!"
    
  
  reusable:
    needs: test_code
    uses: eriweb-demos/workflow-reusable/.github/workflows/demo.yaml@main
    with:
      name: 'advanced workflow'